package com.mr486.generator.pipeline;

import com.mr486.generator.zip.GeneratedFile;
import org.junit.jupiter.api.Test;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;

class TemplateLoaderTest {

    private final TemplateLoader loader = new TemplateLoader();

    @Test
    void loads_hidden_dotfiles() {
        List<GeneratedFile> files = loader.load();
        // .gitignore is excluded by Maven's default resource excludes unless disabled in the pom;
        // .env must survive the directory walk too. Both are required by the generated platform.
        assertThat(files).anyMatch(f -> f.path().equals("ms-platform/.gitignore"));
        assertThat(files).anyMatch(f -> f.path().equals("ms-platform/.env"));
    }

    @Test
    void loads_nested_files_with_full_relative_path() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).anyMatch(f -> f.path().equals("ms-platform/keycloak/import/ms-realm-realm.json"));
        assertThat(files).anyMatch(f -> f.path().equals("ms-platform/pom.xml"));
    }

    @Test
    void loads_every_template_file() {
        // Parity guard: number of non-directory files shipped in templates/ms-platform/.
        assertThat(loader.load()).hasSize(173);
    }

    @Test
    void loads_non_empty_file_list() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).isNotEmpty();
    }

    @Test
    void all_entries_have_ms_platform_prefix() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).allMatch(f -> f.path().startsWith("ms-platform/"));
    }

    @Test
    void no_directory_entries() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).allMatch(f -> !f.path().endsWith("/"));
    }

    @Test
    void marks_sh_files_as_executable() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).anyMatch(f -> f.path().endsWith(".sh") && f.executable());
    }

    @Test
    void template_has_no_dev_artifacts() {
        List<GeneratedFile> files = loader.load();
        assertThat(files).noneMatch(f -> f.path().contains("/benchmark-results/"));
        assertThat(files).noneMatch(f -> f.path().endsWith("/apply-v5.5-step1-loki-promtail.sh"));
        assertThat(files).noneMatch(f -> f.path().endsWith("/go.sh"));
        assertThat(files).noneMatch(f -> f.path().contains(".kate-swp"));
        // One-off patch notes and a runtime artifact (regenerated by test-all.sh) must not ship.
        assertThat(files).noneMatch(f -> f.path().endsWith("/README-PATCH.md"));
        assertThat(files).noneMatch(f -> f.path().endsWith("/README-LOKI-FIX.md"));
        assertThat(files).noneMatch(f -> f.path().endsWith("/tokens.env"));
    }

    @Test
    void marks_mvnw_as_executable() {
        List<GeneratedFile> files = loader.load();
        // Verify that if mvnw exists in the template, it should be marked executable
        // (This test documents the expected behavior even if mvnw is not in current template)
        assertThat(files)
            .noneMatch(f -> f.path().endsWith("mvnw") && !f.executable());
    }
}
