package com.mr486.generator.pipeline.processor;

import com.mr486.generator.dto.IdType;
import com.mr486.generator.dto.ResourceModuleRequest;
import org.springframework.stereotype.Component;

/**
 * Stratégie d'identifiant {@code UUID} : substitue {@code Long}/{@code BIGINT IDENTITY} par
 * {@code UUID}/{@code gen_random_uuid()} dans l'entité, le repository, les DTO/contrôleurs, le SQL,
 * et ajoute l'import {@code java.util.UUID} aux sources Java concernées.
 */
@Component
public class UuidIdVariant implements IdVariant {

    @Override
    public IdType type() {
        return IdType.UUID;
    }

    @Override
    public String apply(String text, String path, ResourceModuleRequest res) {
        String result = text
            // Entity
            .replace(
                "@Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id",
                "@Id\n    @GeneratedValue(strategy = GenerationType.UUID)\n    private UUID id")
            // Repository generic (reformatted templates use the spaced form)
            .replace("JpaRepository<" + res.getClassName() + ", Long>",
                     "JpaRepository<" + res.getClassName() + ", UUID>")
            // DTO, service method params and controller path vars
            .replace("Long id", "UUID id");
        // SQL: BIGINT GENERATED BY DEFAULT AS IDENTITY → UUID DEFAULT gen_random_uuid()
        if (path.endsWith(".sql")) {
            result = result.replace(
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                "UUID DEFAULT gen_random_uuid() PRIMARY KEY");
        }
        // Any Java source now referencing UUID (entity, DTO, repository) needs the import.
        if (path.endsWith(".java") && result.contains("UUID") && !result.contains("import java.util.UUID")) {
            result = result.replaceFirst("(package [^;]+;\n)", "$1import java.util.UUID;\n");
        }
        return result;
    }
}
