server:
  port: ${MS_CLIENT_PORT:8090}
spring:
  application:
    name: ms-client
  session:
    store-type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false
gateway:
  url: ${GATEWAY_URL:http://localhost:9000}
  public-url: ${GATEWAY_PUBLIC_URL:http://localhost:9000}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info
client:
  resources:
    - serviceName: service-a
      routePrefix: /api/resources-a
      label: Service A
      role: USER_SERVICE_A
    - serviceName: service-b
      routePrefix: /api/resources-b
      label: Service B
      role: USER_SERVICE_B
    - serviceName: service-c
      routePrefix: /api/resources-c
      label: Service C
      role: USER_SERVICE_C
  keycloak-account-url: ${KEYCLOAK_ACCOUNT_URL:http://localhost:8089/realms/ms-platform/account}
