package com.mr486.generator.pipeline.processor;

import com.mr486.generator.dto.*;
import com.mr486.generator.model.GenerationContext;
import com.mr486.generator.zip.GeneratedFile;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static com.mr486.generator.pipeline.processor.ProcessorTestHelper.*;

class ResourceExpandProcessorTest {

    private final ResourceExpandProcessor processor = new ResourceExpandProcessor();

    // Simulates service-a files (after PackagePlaceholderProcessor)
    private List<GeneratedFile> serviceAFiles(String root) {
        String base = root + "/service-a/";
        String javaPkg = base + "src/main/java/com/mr486/msplatform/servicea/";
        return new ArrayList<>(List.of(
            file(base + "pom.xml", "<artifactId>service-a</artifactId><dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.liquibase</groupId><artifactId>liquibase-core</artifactId></dependency>"),
            file(base + "Dockerfile", "FROM eclipse-temurin:17-jre-jammy"),
            file(javaPkg + "ServiceAApplication.java", "package com.mr486.msplatform.servicea;\npublic class ServiceAApplication{}"),
            file(javaPkg + "entity/ResourceA.java",
                "package com.mr486.msplatform.servicea.entity;\n"
              + "import jakarta.persistence.*;\n"
              + "@Entity @Table(name=\"resources_a\")\n"
              + "public class ResourceA {\n\n"
              + "    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n"
              + "    private String name;\n}"),
            file(javaPkg + "repository/ResourceARepository.java",
                "package com.mr486.msplatform.servicea.repository;\n"
              + "import org.springframework.data.jpa.repository.JpaRepository;\n"
              + "public interface ResourceARepository extends JpaRepository<ResourceA, Long> {\n}"),
            file(javaPkg + "dto/ResourceADto.java", "package com.mr486.msplatform.servicea.dto;\npublic class ResourceADto{ private Long id; private String name; }"),
            file(javaPkg + "controller/ResourceAController.java", "package com.mr486.msplatform.servicea.controller;\n@RequestMapping(\"/api/resources-a\")\npublic class ResourceAController{}"),
            file(javaPkg + "service/ResourceAService.java", "package com.mr486.msplatform.servicea.service;\nimport com.mr486.msplatform.servicea.entity.ResourceA;\nimport com.mr486.msplatform.servicea.repository.ResourceARepository;\npublic class ResourceAService{ ResourceA build(){return ResourceA.builder().build();} }"),
            file(base + "src/main/resources/application.yml",
                "spring:\n  application:\n    name: service-a\n  datasource:\n    url: ${SERVICE_A_DATASOURCE_URL:jdbc:postgresql://localhost:5432/service_a_db}\n    driver-class-name: org.postgresql.Driver"),
            file(base + "src/main/resources/db/changelog/001-init.sql",
                "CREATE TABLE IF NOT EXISTS resources_a (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL);"),
            file(base + "src/main/resources/db/changelog/002-seed.sql",
                "INSERT INTO resources_a (name) VALUES ('A') ON CONFLICT(name) DO NOTHING;"),
            // patch subdirs that must NOT be cloned
            file(root + "/service-a/service-batch/pom.xml", "patch"),
            file(root + "/service-a/service-consumer/pom.xml", "patch"),
            // service-b and service-c to remove if resources non-empty
            file(root + "/service-b/pom.xml", "<artifactId>service-b</artifactId>"),
            file(root + "/service-c/pom.xml", "<artifactId>service-c</artifactId>")
        ));
    }

    private ResourceModuleRequest resource(String serviceName, String className, String route,
                                           DatabaseType db, IdType id) {
        ResourceModuleRequest r = new ResourceModuleRequest();
        r.setServiceName(serviceName); r.setClassName(className);
        r.setRoutePrefix(route); r.setDatabaseType(db); r.setIdType(id);
        return r;
    }

    private GenerationContext ctxWithResources(List<ResourceModuleRequest> resources) {
        PlatformGenerationRequest req = new PlatformGenerationRequest();
        req.setResources(resources);
        return GenerationContext.from(req);
    }

    @Test
    void noop_when_resources_empty() {
        GenerationContext ctx = defaultCtx();
        List<GeneratedFile> input = serviceAFiles("ms-platform");
        List<GeneratedFile> result = processor.process(input, ctx);
        assertThat(result).hasSize(input.size());
    }

    @Test
    void removes_default_services_when_resources_provided() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).noneMatch(f -> f.path().contains("/service-a/") && !f.path().contains("/service-a/service-batch/") && !f.path().contains("/service-a/service-consumer/"));
        assertThat(result).noneMatch(f -> f.path().contains("/service-b/"));
        assertThat(result).noneMatch(f -> f.path().contains("/service-c/"));
    }

    @Test
    void generates_service_with_correct_name_in_paths() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/"));
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/") && f.path().endsWith("Application.java"));
    }

    @Test
    void null_routePrefix_defaults_to_api_plural() {
        ResourceModuleRequest r = new ResourceModuleRequest();
        r.setServiceName("order-service"); r.setClassName("Order");
        // routePrefix left null
        r.setDatabaseType(DatabaseType.POSTGRES); r.setIdType(IdType.LONG);
        GenerationContext ctx = ctxWithResources(List.of(r));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        result.stream()
            .filter(f -> f.path().endsWith("OrderController.java"))
            .forEach(f -> {
                assertThat(contentOf(f)).contains("/api/orders");
                assertThat(contentOf(f)).doesNotContain("/api/resources-a");
            });
    }

    @Test
    void replaces_ResourceA_with_className_in_content() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        result.stream()
            .filter(f -> f.path().contains("/invoice/") && f.path().endsWith(".java"))
            .forEach(f -> {
                assertThat(contentOf(f)).doesNotContain("ResourceA");
                assertThat(contentOf(f)).doesNotContain("service-a");
            });
    }

    @Test
    void generates_multiple_services() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG),
            resource("product", "Product", "/api/products", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/"));
        assertThat(result).anyMatch(f -> f.path().contains("/product/"));
    }

    @Test
    void does_not_clone_patch_subdirs() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        // patch service-a/service-batch/ and service-a/service-consumer/ must NOT be cloned
        assertThat(result).noneMatch(f -> f.path().startsWith("ms-platform/invoice/service-batch/"));
        assertThat(result).noneMatch(f -> f.path().startsWith("ms-platform/invoice/service-consumer/"));
    }

    @Test
    void h2_replaces_postgres_driver_in_pom() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("inventory", "Item", "/api/items", DatabaseType.H2, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile pom = result.stream()
            .filter(f -> f.path().endsWith("inventory/pom.xml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(pom)).contains("h2");
        assertThat(contentOf(pom)).doesNotContain("postgresql");
    }

    @Test
    void h2_replaces_datasource_in_application_yml() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("inventory", "Item", "/api/items", DatabaseType.H2, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile yml = result.stream()
            .filter(f -> f.path().endsWith("inventory/src/main/resources/application.yml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(yml)).contains("jdbc:h2:mem:");
        assertThat(contentOf(yml)).contains("org.h2.Driver");
        assertThat(contentOf(yml)).doesNotContain("org.postgresql.Driver");
    }

    @Test
    void h2_strips_on_conflict_clause_from_seed_sql() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("inventory", "Item", "/api/items", DatabaseType.H2, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile seed = result.stream()
            .filter(f -> f.path().endsWith("inventory/src/main/resources/db/changelog/002-seed.sql"))
            .findFirst().orElseThrow();
        assertThat(contentOf(seed)).doesNotContain("ON CONFLICT");
        assertThat(contentOf(seed)).contains("INSERT INTO items");
        assertThat(contentOf(seed)).endsWith(";");
    }

    @Test
    void mongo_renames_entity_dir_to_document() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).anyMatch(f -> f.path().contains("/catalog/") && f.path().contains("/document/"));
        assertThat(result).noneMatch(f -> f.path().contains("/catalog/") && f.path().contains("/entity/"));
    }

    @Test
    void mongo_entity_uses_document_annotation() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile doc = result.stream()
            .filter(f -> f.path().contains("/catalog/") && f.path().contains("/document/Product.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(doc)).contains("@Document");
        assertThat(contentOf(doc)).doesNotContain("@Entity");
        assertThat(contentOf(doc)).contains("private String id");
    }

    @Test
    void mongo_repository_extends_MongoRepository() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile repo = result.stream()
            .filter(f -> f.path().contains("/catalog/") && f.path().endsWith("Repository.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(repo)).contains("MongoRepository");
        assertThat(contentOf(repo)).doesNotContain("JpaRepository");
    }

    @Test
    void mongo_pom_contains_mongodb_not_jpa() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile pom = result.stream()
            .filter(f -> f.path().endsWith("catalog/pom.xml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(pom)).contains("spring-boot-starter-data-mongodb");
        assertThat(contentOf(pom)).doesNotContain("spring-boot-starter-data-jpa");
        assertThat(contentOf(pom)).doesNotContain("postgresql");
    }

    @Test
    void mongo_application_yml_has_mongodb_uri_not_datasource() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile yml = result.stream()
            .filter(f -> f.path().endsWith("catalog/src/main/resources/application.yml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(yml)).contains("mongodb:");
        assertThat(contentOf(yml)).doesNotContain("datasource:");
    }

    @Test
    void mongo_application_yml_uses_valid_single_brace_placeholders() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile yml = result.stream()
            .filter(f -> f.path().endsWith("catalog/src/main/resources/application.yml"))
            .findFirst().orElseThrow();
        String s = contentOf(yml);
        // ${{...}} is an invalid Spring placeholder: it resolves the inner and leaves a
        // dangling brace (e.g. "port: 8080}"), which breaks startup.
        assertThat(s).doesNotContain("${{");
        assertThat(s).contains("port: ${CATALOG_PORT:8080}");
        assertThat(s).contains("${CATALOG_MONGO_URI:");
    }

    @Test
    void mongo_removes_db_changelog_files() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).noneMatch(f -> f.path().contains("/catalog/") && f.path().contains("/db/changelog/"));
    }

    @Test
    void integer_replaces_Long_with_Integer_in_entity() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.INTEGER)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile entity = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().contains("/entity/"))
            .findFirst().orElseThrow();
        assertThat(contentOf(entity)).contains("private Integer id");
        assertThat(contentOf(entity)).doesNotContain("private Long id");
    }

    @Test
    void integer_replaces_Long_in_repository_generic() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.INTEGER)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile repo = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().endsWith("Repository.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(repo)).contains("JpaRepository<Order, Integer>");
        assertThat(contentOf(repo)).doesNotContain("JpaRepository<Order, Long>");
    }

    @Test
    void uuid_adds_UUID_type_and_generation_strategy() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.UUID)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile entity = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().contains("/entity/"))
            .findFirst().orElseThrow();
        assertThat(contentOf(entity)).contains("private UUID id");
        assertThat(contentOf(entity)).contains("GenerationType.UUID");
        assertThat(contentOf(entity)).contains("import java.util.UUID");
    }

    @Test
    void uuid_adds_UUID_import_to_dto() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.UUID)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile dto = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().endsWith("Dto.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(dto)).contains("private UUID id");
        assertThat(contentOf(dto)).contains("import java.util.UUID");
    }

    @Test
    void uuid_adds_UUID_import_to_repository() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.UUID)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile repo = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().endsWith("Repository.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(repo)).contains("JpaRepository<Order, UUID>");
        assertThat(contentOf(repo)).contains("import java.util.UUID");
    }

    @Test
    void uuid_replaces_BIGINT_with_UUID_in_sql() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("order", "Order", "/api/orders", DatabaseType.POSTGRES, IdType.UUID)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile sql = result.stream()
            .filter(f -> f.path().contains("/order/") && f.path().endsWith("001-init.sql"))
            .findFirst().orElseThrow();
        assertThat(contentOf(sql)).contains("UUID DEFAULT gen_random_uuid() PRIMARY KEY");
        assertThat(contentOf(sql)).doesNotContain("BIGINT");
    }

    @Test
    void mongo_service_imports_document_not_entity() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile svc = result.stream()
            .filter(f -> f.path().contains("/catalog/") && f.path().endsWith("ProductService.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(svc)).contains(".document.Product");
        assertThat(contentOf(svc)).doesNotContain(".entity.");
    }

    @Test
    void mongo_dto_uses_string_id_not_long() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile dto = result.stream()
            .filter(f -> f.path().contains("/catalog/") && f.path().endsWith("Dto.java"))
            .findFirst().orElseThrow();
        assertThat(contentOf(dto)).contains("private String id");
        assertThat(contentOf(dto)).doesNotContain("private Long id");
    }

    @Test
    void mongo_idType_is_always_string_regardless_of_request() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("catalog", "Product", "/api/products", DatabaseType.MONGO, IdType.UUID)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile doc = result.stream()
            .filter(f -> f.path().contains("/catalog/") && f.path().contains("/document/"))
            .findFirst().orElseThrow();
        assertThat(contentOf(doc)).contains("private String id");
        assertThat(contentOf(doc)).doesNotContain("private UUID id");
    }
}
