package com.mr486.generator.pipeline.processor;

import static com.mr486.generator.pipeline.processor.ProcessorTestHelper.file;

import com.mr486.generator.dto.DatabaseType;
import com.mr486.generator.dto.IdType;
import com.mr486.generator.dto.PlatformGenerationRequest;
import com.mr486.generator.dto.ResourceModuleRequest;
import com.mr486.generator.model.GenerationContext;
import com.mr486.generator.zip.GeneratedFile;
import java.util.ArrayList;
import java.util.List;

/**
 * Fixtures partagées des tests de {@link ResourceExpandProcessor} : le module {@code service-a}
 * simulé (après {@link PackagePlaceholderProcessor}), la fabrique de ressources et le contexte.
 *
 * <p>Extraites d'une classe de test unique devenue trop grosse ; consommées par les tests de base,
 * H2, Mongo et types d'identifiant.
 */
final class ResourceExpandFixtures {

    private ResourceExpandFixtures() {
    }

    // Processor câblé comme le fait Spring (stratégies de base et d'identifiant).
    static ResourceExpandProcessor processor() {
        return new ResourceExpandProcessor(
            List.of(new PostgresVariant(), new H2Variant(), new MongoVariant()),
            List.of(new IntegerIdVariant(), new UuidIdVariant()));
    }

    // Fichiers du module service-a simulé (après substitution de package).
    static List<GeneratedFile> serviceAFiles(String root) {
        String base = root + "/service-a/";
        String javaPkg = base + "src/main/java/com/mr486/msplatform/servicea/";
        // fixture: pom.xml is intentionally long (minified XML) — do not reformat
        return new ArrayList<>(List.of(
            file(base + "pom.xml",
                "<artifactId>service-a</artifactId>"
                + "<dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId></dependency>"
                + "<dependency><groupId>org.springframework.boot</groupId>"
                + "<artifactId>spring-boot-starter-data-jpa</artifactId></dependency>"
                + "<dependency><groupId>org.liquibase</groupId><artifactId>liquibase-core</artifactId></dependency>"),
            file(base + "Dockerfile", "FROM eclipse-temurin:17-jre-jammy"),
            file(javaPkg + "ServiceAApplication.java",
                "package com.mr486.msplatform.servicea;\npublic class ServiceAApplication{}"),
            file(javaPkg + "entity/ResourceA.java",
                "package com.mr486.msplatform.servicea.entity;\n"
              + "import jakarta.persistence.*;\n"
              + "@Entity @Table(name=\"resources_a\")\n"
              + "public class ResourceA {\n\n"
              + "    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n"
              + "    private String name;\n}"),
            file(javaPkg + "repository/ResourceARepository.java",
                "package com.mr486.msplatform.servicea.repository;\n"
              + "import org.springframework.data.jpa.repository.JpaRepository;\n"
              + "public interface ResourceARepository extends JpaRepository<ResourceA, Long> {\n}"),
            file(javaPkg + "dto/ResourceADto.java",
                "package com.mr486.msplatform.servicea.dto;\n"
              + "public class ResourceADto{ private Long id; private String name; }"),
            file(javaPkg + "controller/ResourceAController.java",
                "package com.mr486.msplatform.servicea.controller;\n"
              + "@RequestMapping(\"/api/resources-a\")\n"
              + "public class ResourceAController{}"),
            // fixture: service file is intentionally long (minified Java) — do not reformat
            file(javaPkg + "service/ResourceAService.java",
                "package com.mr486.msplatform.servicea.service;\n"
              + "import com.mr486.msplatform.servicea.entity.ResourceA;\n"
              + "import com.mr486.msplatform.servicea.repository.ResourceARepository;\n"
              + "public class ResourceAService{ ResourceA build(){return ResourceA.builder().build();} }"),
            file(base + "src/main/resources/application.yml",
                "spring:\n  application:\n    name: service-a\n  datasource:\n"
              + "    url: ${SERVICE_A_DATASOURCE_URL:jdbc:postgresql://localhost:5432/service_a_db}\n"
              + "    driver-class-name: org.postgresql.Driver"),
            file(base + "src/main/resources/db/changelog/001-init.sql",
                "CREATE TABLE IF NOT EXISTS resources_a "
              + "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL);"),
            file(base + "src/main/resources/db/changelog/002-seed.sql",
                "INSERT INTO resources_a (name) VALUES ('A') ON CONFLICT(name) DO NOTHING;"),
            // patch subdirs that must NOT be cloned
            file(root + "/service-a/service-batch/pom.xml", "patch"),
            file(root + "/service-a/service-consumer/pom.xml", "patch"),
            // service-b and service-c to remove if resources non-empty
            file(root + "/service-b/pom.xml", "<artifactId>service-b</artifactId>"),
            file(root + "/service-c/pom.xml", "<artifactId>service-c</artifactId>")
        ));
    }

    // Variante du fixture où ResourceAService porte des paramètres d'id Long réalistes.
    static List<GeneratedFile> serviceAFilesWithServiceParams(String root) {
        List<GeneratedFile> files = new ArrayList<>(serviceAFiles(root));
        String svcPath = root
            + "/service-a/src/main/java/com/mr486/msplatform/servicea/service/ResourceAService.java";
        files.removeIf(f -> f.path().equals(svcPath));
        files.add(file(svcPath,
            "package com.mr486.msplatform.servicea.service;\n" +
            "public class ResourceAService{\n" +
            "  public ResourceADto findById(Long id){return toDto(repository.findById(id).orElseThrow());}\n" +
            "  public ResourceADto update(Long id,ResourceADto dto)"
            + "{ ResourceA e=repository.findById(id).orElseThrow(); return toDto(repository.save(e)); }\n" +
            "  public void delete(Long id){ repository.deleteById(id); }\n" +
            "}"));
        return files;
    }

    // Fabrique une ressource métier avec ses variantes de base et d'identifiant.
    static ResourceModuleRequest resource(String serviceName, String className, String route,
                                          DatabaseType db, IdType id) {
        ResourceModuleRequest r = new ResourceModuleRequest();
        r.setServiceName(serviceName);
        r.setClassName(className);
        r.setRoutePrefix(route);
        r.setDatabaseType(db);
        r.setIdType(id);
        return r;
    }

    // Contexte de génération portant la liste de ressources demandée.
    static GenerationContext ctxWithResources(List<ResourceModuleRequest> resources) {
        PlatformGenerationRequest req = new PlatformGenerationRequest();
        req.setResources(resources);
        return GenerationContext.from(req);
    }
}
