package com.mr486.generator.pipeline.processor;

import com.mr486.generator.dto.*;
import com.mr486.generator.model.GenerationContext;
import com.mr486.generator.zip.GeneratedFile;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static com.mr486.generator.pipeline.processor.ProcessorTestHelper.*;

class ResourceExpandProcessorTest {

    private final ResourceExpandProcessor processor = new ResourceExpandProcessor();

    // Simulates service-a files (after PackagePlaceholderProcessor)
    private List<GeneratedFile> serviceAFiles(String root) {
        String base = root + "/service-a/";
        String javaPkg = base + "src/main/java/com/mr486/msplatform/servicea/";
        return new ArrayList<>(List.of(
            file(base + "pom.xml", "<artifactId>service-a</artifactId><dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.liquibase</groupId><artifactId>liquibase-core</artifactId></dependency>"),
            file(base + "Dockerfile", "FROM eclipse-temurin:17-jre-jammy"),
            file(javaPkg + "ServiceAApplication.java", "package com.mr486.msplatform.servicea;\npublic class ServiceAApplication{}"),
            file(javaPkg + "entity/ResourceA.java", "package com.mr486.msplatform.servicea.entity;\nimport jakarta.persistence.*;\n@Entity @Table(name=\"resources_a\")\npublic class ResourceA{ @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; private String name; }"),
            file(javaPkg + "repository/ResourceARepository.java", "package com.mr486.msplatform.servicea.repository;\nimport org.springframework.data.jpa.repository.JpaRepository;\npublic interface ResourceARepository extends JpaRepository<ResourceA,Long> {}"),
            file(javaPkg + "dto/ResourceADto.java", "package com.mr486.msplatform.servicea.dto;\npublic class ResourceADto{ private Long id; private String name; }"),
            file(javaPkg + "controller/ResourceAController.java", "package com.mr486.msplatform.servicea.controller;\n@RequestMapping(\"/api/resources-a\")\npublic class ResourceAController{}"),
            file(javaPkg + "service/ResourceAService.java", "package com.mr486.msplatform.servicea.service;\npublic class ResourceAService{}"),
            file(base + "src/main/resources/application.yml",
                "spring:\n  application:\n    name: service-a\n  datasource:\n    url: ${SERVICE_A_DATASOURCE_URL:jdbc:postgresql://localhost:5432/service_a_db}\n    driver-class-name: org.postgresql.Driver"),
            file(base + "src/main/resources/db/changelog/001-init.sql",
                "CREATE TABLE IF NOT EXISTS resources_a (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL);"),
            // patch subdirs that must NOT be cloned
            file(root + "/service-a/service-batch/pom.xml", "patch"),
            file(root + "/service-a/service-consumer/pom.xml", "patch"),
            // service-b and service-c to remove if resources non-empty
            file(root + "/service-b/pom.xml", "<artifactId>service-b</artifactId>"),
            file(root + "/service-c/pom.xml", "<artifactId>service-c</artifactId>")
        ));
    }

    private ResourceModuleRequest resource(String serviceName, String className, String route,
                                           DatabaseType db, IdType id) {
        ResourceModuleRequest r = new ResourceModuleRequest();
        r.setServiceName(serviceName); r.setClassName(className);
        r.setRoutePrefix(route); r.setDatabaseType(db); r.setIdType(id);
        return r;
    }

    private GenerationContext ctxWithResources(List<ResourceModuleRequest> resources) {
        PlatformGenerationRequest req = new PlatformGenerationRequest();
        req.setResources(resources);
        return GenerationContext.from(req);
    }

    @Test
    void noop_when_resources_empty() {
        GenerationContext ctx = defaultCtx();
        List<GeneratedFile> input = serviceAFiles("ms-platform");
        List<GeneratedFile> result = processor.process(input, ctx);
        assertThat(result).hasSize(input.size());
    }

    @Test
    void removes_default_services_when_resources_provided() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).noneMatch(f -> f.path().contains("/service-a/") && !f.path().contains("/service-a/service-batch/") && !f.path().contains("/service-a/service-consumer/"));
        assertThat(result).noneMatch(f -> f.path().contains("/service-b/"));
        assertThat(result).noneMatch(f -> f.path().contains("/service-c/"));
    }

    @Test
    void generates_service_with_correct_name_in_paths() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/"));
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/") && f.path().endsWith("Application.java"));
    }

    @Test
    void replaces_ResourceA_with_className_in_content() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        result.stream()
            .filter(f -> f.path().contains("/invoice/") && f.path().endsWith(".java"))
            .forEach(f -> {
                assertThat(contentOf(f)).doesNotContain("ResourceA");
                assertThat(contentOf(f)).doesNotContain("service-a");
            });
    }

    @Test
    void generates_multiple_services() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG),
            resource("product", "Product", "/api/products", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        assertThat(result).anyMatch(f -> f.path().contains("/invoice/"));
        assertThat(result).anyMatch(f -> f.path().contains("/product/"));
    }

    @Test
    void does_not_clone_patch_subdirs() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("invoice", "Invoice", "/api/invoices", DatabaseType.POSTGRES, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        // patch service-a/service-batch/ and service-a/service-consumer/ must NOT be cloned
        assertThat(result).noneMatch(f -> f.path().startsWith("ms-platform/invoice/service-batch/"));
        assertThat(result).noneMatch(f -> f.path().startsWith("ms-platform/invoice/service-consumer/"));
    }

    @Test
    void h2_replaces_postgres_driver_in_pom() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("inventory", "Item", "/api/items", DatabaseType.H2, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile pom = result.stream()
            .filter(f -> f.path().endsWith("inventory/pom.xml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(pom)).contains("h2");
        assertThat(contentOf(pom)).doesNotContain("postgresql");
    }

    @Test
    void h2_replaces_datasource_in_application_yml() {
        GenerationContext ctx = ctxWithResources(List.of(
            resource("inventory", "Item", "/api/items", DatabaseType.H2, IdType.LONG)
        ));
        List<GeneratedFile> result = processor.process(serviceAFiles("ms-platform"), ctx);
        GeneratedFile yml = result.stream()
            .filter(f -> f.path().endsWith("inventory/src/main/resources/application.yml"))
            .findFirst().orElseThrow();
        assertThat(contentOf(yml)).contains("jdbc:h2:mem:");
        assertThat(contentOf(yml)).contains("org.h2.Driver");
        assertThat(contentOf(yml)).doesNotContain("org.postgresql.Driver");
    }
}
